### ISSUE TITLE
ntfromstruct could optionally store type as a field of NamedTuple

### ISSUE THREAD

**Issue by scls19fr** [JeffreySarnoff/NamedTupleTools.jl#14]
Hello,

In your example 

# Struct construction, conversion
```
using NamedTupleTools

julia> struct MyStruct
           tally::Int
           team::String
       end

julia> mystruct = MyStruct(5, "hometeam")
MyStruct(5, "hometeam")

julia> mynamedtuple = ntfromstruct(mystruct)
(tally = 5, team = "hometeam")
```

it could be useful to have an option for `ntfromstruct` function to preserve type name (probably as a Symbol)

```
julia> mynamedtuple = ntfromstruct(mystruct, keep_type=true)
(type = :MyStruct, tally = 5, team = "hometeam")
```

Kind regards

**Comment by JeffreySarnoff** [comment]
hmmm

**Comment by scls19fr** [comment]
```julia
julia> merge((type=Symbol(typeof(mystruct)),), ntfromstruct(mystruct))
(type = :MyStruct, tally = 5, team = "hometeam")
```

**Comment by JeffreySarnoff** [comment]
why did you close this?
I have been working on a version that handles both ways.

Jeffrey Sarnoff

**Comment by JeffreySarnoff** [comment]
Implemented as an option in version 1 (wip).  Thank you.

**Comment by JeffreySarnoff** [comment]
you are credited in the v1 Readme

**Comment by scls19fr** [comment]
Sorry @JeffreySarnoff but I don't see a PR or a commit linking to this issue.

**Comment by JeffreySarnoff** [comment]
It was a suggestion of yours https://github.com/JeffreySarnoff/NamedTupleTools.jl/issues/14
The implementation is in the v1 branch, which is a work in progress.  The credit is here (last entry) https://github.com/JeffreySarnoff/NamedTupleTools.jl/blob/v1/README.md#credits

**Comment by scls19fr** [comment]
ok in the [v1 branch](https://github.com/JeffreySarnoff/NamedTupleTools.jl/tree/v1)
I didn't understand what you mean by v1.
Thanks @JeffreySarnoff
