### ISSUE TITLE
Allow merge of arbitrary NamedTuples

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JeffreySarnoff/NamedTupleTools.jl#2]
currently `merge` allows only merging of two named tuples.

**Comment by JeffreySarnoff** [comment]
good thought; I will add that.

if you need that today:
```reduce(merge,(nt1,nt2,nt3,nt4))```

**Comment by JeffreySarnoff** [comment]
now it supports merging 2..7 named tuples -- not arbitrary, but should suffice
