### ISSUE TITLE
Do not define `propertynames`

### ISSUE THREAD

**Issue by goretkin** [JeffreySarnoff/NamedTupleTools.jl#31]
https://github.com/JeffreySarnoff/NamedTupleTools.jl/blob/7ef96c484a5d69a6a3dacb58eb03e0547fe12f3c/src/NamedTupleTools.jl#L41 isn't needed anymore

```julia
julia> propertynames((x=3,y=5))
(:x, :y)
```

**Comment by JeffreySarnoff** [comment]
thank you. will fix.

**Comment by JeffreySarnoff** [comment]
fixedd in #generated branch (next  release)
