### ISSUE TITLE
Error in merge_recursive doc string?

### ISSUE THREAD

**Issue by danielmatz** [JeffreySarnoff/NamedTupleTools.jl#41]
The doc string for `merge_recursive` says that it propagates the value from the leftmost `NamedTuple` argument:

https://github.com/JeffreySarnoff/NamedTupleTools.jl/blob/9eedb5da218f60296429372e423c9c18c9d502f5/src/NamedTupleTools.jl#L317

However, the examples given and the code itself appear to propagate the value from the rightmost argument. And that would also match the convention in `merge`.

Is this just a typo?

**Comment by JeffreySarnoff** [comment]
yes. thank you.

**Comment by JeffreySarnoff** [comment]
actually hold on ...

**Comment by JeffreySarnoff** [comment]
ok revised, pending merge
