### ISSUE TITLE
Warnings in Julia v1.9

### ISSUE THREAD

**Issue by juliohm** [JeffreySarnoff/NamedTupleTools.jl#47]
WARNING: method definition for namedtuple at C:\Users\julio\.julia\packages\NamedTupleTools\GZxRn\src\NamedTupleTools.jl:165 declares type variable N but does not use it.
WARNING: method definition for delete at C:\Users\julio\.julia\packages\NamedTupleTools\GZxRn\src\NamedTupleTools.jl:258 declares type variable N but does not use it.

**Comment by JeffreySarnoff** [comment]
thank you

**Comment by JeffreySarnoff** [comment]
I made a change -- the error message is overzealous, let me know if this current version fixes the warning.
