### ISSUE TITLE
getprototype

### ISSUE THREAD

**Issue by cscherrer** [JeffreySarnoff/NamedTupleTools.jl#9]
Here's another one that seems useful:

```julia
julia> getprototype(::NamedTuple{A,B}) where {A,B} = NamedTuple{A}
getprototype (generic function with 1 method)

julia> (a=1,b=2) |> getprototype
NamedTuple{(:a, :b),T} where T<:Tuple
```

Should have a chance to PR later today, noting here so I don't forget :)

**Comment by JeffreySarnoff** [comment]
I have added `prototype` for your `getprototype` in master, with credit, releasing soon.
